version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    env_file:
      - .env.docker
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - adoptme-network

  mongo:
    image: mongo:6.0
    container_name: adoptme-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: adoptme
    volumes:
      - mongodb_data:/data/db
    networks:
      - adoptme-network

networks:
  adoptme-network:
    driver: bridge

volumes:
  mongodb_data:
